#!/usr/bin/env bash
#install NGINX web server
apt install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start

# Configure Nginx server so that /redirect_me 
# is redirecting to another page.
sudo sed -i '24i\       rewrite ^/redirect_me https://google.com permanent;' /etc/nginx/sites-available/default
systemctl restart nginx
