#!/usr/bin/env bash
# Configure a new server to run NGINX

sudo apt-get update
sudo apt-get install -y nginx

# Index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Redirect /redirect_me path to google
replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/google.com permanent;"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

# error 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/not_found.html
replacement="server_name _;\n\terror_page 404 \/not_found.html;\n\tlocation = \/not_found.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

# add a header member that endicating server hostname
replacement="server_name _;\n\tadd_header X-Served-By $(hostname);"
sudo sed -i "s/server_name _;/$replacement/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
