#!/usr/bin/env bash
# Install and configure HAproxy on a server

sudo apt install haproxy -y

echo -e "frontend http80\n"\
"        bind *:80\n"\
"        mode http\n"\
"        default_backend lb\n"\
""\
"backend lb\n"\
"        mode http\n"\
"	 balance roundrobin"
"        server web-01 18.206.208.23\n"\
"        server web-02 54.210.152.224\n" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

service haproxy restart
