#!/bin/bash

if [ $(grep -c "add_header X-Served-By" file) -eq 1 ]
then
	sed -s "s/X-Served-By .*/X-Served-By $(hostname);/" file
	echo "111111111111111111111"
else
	costum_header="add_header x-served-by $(hostname);"
	sed -s "/server_name _;/a $costum_header" file
fi
